### ISSUE TITLE
Migrate from Geotoolkit-pending to Apache SIS

### ISSUE THREAD

**Issue by eblondel** [openfigis/gis-tools#4]
Geotk is being migrated to Apache SIS (http://sis.apache.org), at now metadata module is yet migrated under Apache SIS 0.3.

The plan of Geotk developers is to keep Geotk as a "laboratory" for Apache SIS. Geotk would be built on top of SIS, and Geotk classes are expected to migrate to SIS when they are considered mature enough. When a Geotk class migrate to SIS, the Geotk one is deprecated before deletion.

Consequences:
- replace "import org.geotoolkit..." by "import org.apache.sis..." (most class names are identical).
- Some exceptions are SimpleInternationalString which is located in org.apache.sis.util.iso (an "iso" sub-package has been added), and Anchor which is handled in a slightly different way

**Comment by eblondel** [comment]
At now, the Apache SIS stable 0.3 release contains the following modules:
- sis-metadata (~geotk-metadata)
- sis-referencing (~geotk-referencing)
- sis-utility (~geotk-utility)

The snapshot 0.4 also contains sis-shapefile / sis-feature modules, but it seems they are not mature enough to migrate from Geotoolkit. The gis-metadata module uses the geotk-shapefile module as dependency. --> Need to assess if the migration could be done now, or should be postponed.

**Comment by ceefour** [comment]
:+1: (current release is sis 0.6)

**Comment by ceefour** [comment]
I think since this project has been moved to https://github.com/openfigis/gems/issues/17, all issues in gis-tools should be closed.

**Comment by eblondel** [comment]
project moved to https://github.com/openfigis/gems
